# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_vibrrt_wrappers", use_symbols = TRUE, package_name = "vibrrt")

#' @docType package
#' @usage NULL
#' @useDynLib vibrrt, .registration = TRUE
NULL

#' Call Vibrato tokenizer
#' @noRd
vbrt <- function(sentence, sys_dic, user_dic) .Call(wrap__vbrt, sentence, sys_dic, user_dic)


# nolint end
